//
// stackcollapse-redis.go     collapse redis traffic packets into stack like structure for further flame graph generating.
//
// USAGE ./stackcollapse-redis.go dump.pcap > outfile
//
// dump.pcap could be generated by tcpdump -w

package main

import (
	"flag"
	"github.com/google/gopacket/pcap"
	"github.com/google/gopacket"
)

var (
	dumpf string
)

func main() {
	flag.StringVar(&dumpf, "f", "", "tcpdump captured traffic file")
	flag.Parse();
	if len(dumpf) == 0 {
		return;
	}

	handle, _ = pcap.OpenOffline(dumpf)
	packetSource := gopacket.NewPacketSource(handle, handle.LinkType())
	for {
		packet, err := packetSource.NextPacket()
	}
}

